# Generated by Django 5.2.8 on 2025-12-01 15:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habito',
            fields=[
                ('id_habito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puntos', models.IntegerField(default=0)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('dias', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'habitos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id_logro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('puntos', models.IntegerField(default=0)),
                ('condicion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'logros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.TextField(db_column='password_hash')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioLog',
            fields=[
                ('id_log', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField(blank=True, null=True)),
                ('accion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('biografia', models.TextField(blank=True, null=True)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('racha_actual', models.IntegerField(default=0)),
                ('racha_maxima', models.IntegerField(default=0)),
                ('num_habitos_creados', models.IntegerField(default=0)),
                ('habitos_completados', models.IntegerField(default=0)),
                ('num_logros_obtenidos', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'perfiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preferencia',
            fields=[
                ('usuario', models.OneToOneField(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('modo_oscuro', models.BooleanField(default=False)),
                ('notificaciones_push', models.BooleanField(default=False)),
                ('notificaciones_email', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'preferencias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioHabito',
            fields=[
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
            ],
            options={
                'db_table': 'usuario_habito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioLogro',
            fields=[
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('fecha_obtencion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'usuario_logro',
                'managed': False,
            },
        ),
    ]
